version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.2'
    hostname: mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_PASSWORD=magento_db_password
      - MARIADB_DATABASE=bitnami_magento
  magento:
    build: 'docker/'
    volumes:
      - '.:/source'
    ports:
      - '80:80'
      - '443:443'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_PASSWORD=magento_db_password
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - MAGENTO_HOST=localhost
      - MAGENTO_PASSWORD=CHANGEME123
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      - SHOP_PGC_URL=sandbox
      - SHOP_PGC_USER=test-user
      - SHOP_PGC_PASSWORD=test-pass
      - SHOP_PGC_API_KEY=key
      - SHOP_PGC_SECRET=secret
      - SHOP_PGC_INTEGRATION_KEY=intkey
      - BRANCH=master
    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    image: 'bitnami/elasticsearch:6'