version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.2'
    hostname: mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_PASSWORD=magento_db_password
      - MARIADB_DATABASE=bitnami_magento
  magento:
    build: 'docker/'
    volumes:
      - '.:/source'
    ports:
      - '80:80'
      - '443:443'
    environment:
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD}
      - BITNAMI_APP_NAME=${BITNAMI_APP_NAME}
      - BITNAMI_IMAGE_VERSION=${BITNAMI_IMAGE_VERSION}
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - ELASTICSEARCH_PORT_NUMBER=${ELASTICSEARCH_PORT_NUMBER}
      - EXTERNAL_HTTPS_PORT_NUMBER=${EXTERNAL_HTTPS_PORT_NUMBER}
      - EXTERNAL_HTTP_PORT_NUMBER=${EXTERNAL_HTTP_PORT_NUMBER}
      - MAGENTO_ADMINURI=${MAGENTO_ADMINURI}
      - MAGENTO_DATABASE_NAME=${MAGENTO_DATABASE_NAME}
      - MAGENTO_DATABASE_PASSWORD=${MAGENTO_DATABASE_PASSWORD}
      - MAGENTO_DATABASE_USER=${MAGENTO_DATABASE_USER}
      - MAGENTO_EMAIL=${MAGENTO_EMAIL}
      - MAGENTO_FIRSTNAME=${MAGENTO_FIRSTNAME}
      - MAGENTO_HOST=${MAGENTO_HOST}
      - MAGENTO_LASTNAME=${MAGENTO_LASTNAME}
      - MAGENTO_MODE=${MAGENTO_MODE}
      - MAGENTO_PASSWORD=${MAGENTO_PASSWORD}
      - MAGENTO_USERNAME=${MAGENTO_USERNAME}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_PORT_NUMBER=${MARIADB_PORT_NUMBER}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_ROOT_USER=${MARIADB_ROOT_USER}
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=${MYSQL_CLIENT_CREATE_DATABASE_NAME}
      - MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=${MYSQL_CLIENT_CREATE_DATABASE_PASSWORD}
      - MYSQL_CLIENT_CREATE_DATABASE_PRIVILEGES=${MYSQL_CLIENT_CREATE_DATABASE_PRIVILEGES}
      - MYSQL_CLIENT_CREATE_DATABASE_USER=${MYSQL_CLIENT_CREATE_DATABASE_USER}
      - PRECONFIGURE=${PRECONFIGURE}
      - SHOP_PGC_URL=${SHOP_PGC_URL}
      - SHOP_PGC_USER=${SHOP_PGC_USER}
      - SHOP_PGC_PASSWORD=${SHOP_PGC_PASSWORD}
      - SHOP_PGC_API_KEY=${SHOP_PGC_API_KEY}
      - SHOP_PGC_SECRET=${SHOP_PGC_SECRET}
      - SHOP_PGC_INTEGRATION_KEY=${SHOP_PGC_INTEGRATION_KEY}
      - REPOSITORY=${REPOSITORY}
      - BRANCH=${BRANCH}
      - BUILD_ARTIFACT=${BUILD_ARTIFACT}
    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    image: 'bitnami/elasticsearch:6'

volumes:
  undefined: