version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  magento:
    image: 'docker.io/bitnami/magento:2-debian-10'
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MAGENTO_HOST=localhost
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      - ALLOW_EMPTY_PASSWORD=yes
      - HTTPS=false
      - MAGENTO_PASSWORD=${MAGENTO_PASSWORD:-bitnami1}
      - MAGENTO_USERNAME=${MAGENTO_USERNAME:-user}
      - DEMO_CUSTOMER_PASSWORD=${DEMO_CUSTOMER_PASSWORD:-customer}
      - SHOP_PGC_URL=${SHOP_PGC_URL:-sandbox}
      - SHOP_PGC_USER=${SHOP_PGC_USER:-test-user}
      - SHOP_PGC_PASSWORD=${SHOP_PGC_PASSWORD:-test-pass}
      - SHOP_PGC_API_KEY=${SHOP_PGC_API_KEY:-key}
      - SHOP_PGC_SECRET=${SHOP_PGC_SECRET:-secret}
      - SHOP_PGC_INTEGRATION_KEY=${SHOP_PGC_INTEGRATION_KEY:-int_key}
      - SHOP_PGC_SEAMLESS=${SHOP_PGC_SEAMLESS:-1}
      - REPOSITORY=${REPOSITORY:-https://github.com/user/repo}
      - BRANCH=${BRANCH:-master}
    volumes:
      - 'magento_data:/bitnami/magento'
      - './Pgc:/source_code/Pgc:ro,consistent'
      - './docker/link_source.sh:/docker-entrypoint-init.d/link_source.sh:ro'
    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    image: 'docker.io/bitnami/elasticsearch:6-debian-10'
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
  elasticsearch_data:
    driver: local

